### ISSUE TITLE
Unable to compile & Run custom build on Win 8.1

### ISSUE THREAD

**Issue by Annuther** [phonegap/phonegap-app-developer#420] opened 2016-04-27 11:21 UTC
Hi,
Has anyone successfully custom built phonegap-app-developer on Windows 8.1?? i've follwed all the steps in the repo and made minimal changes in config.xml and not installed any plugins. It seems cloning the repo then installing (npm install) causes incompatibility warnings from the outset before attempting to build. Has any Windows user successfully custom built using the repo??

**Comment by timkim** [comment] 2016-04-28 20:29
Hey there @Annuther 

I suppose I can close this issue since it's a duplicate of this one: https://github.com/phonegap/phonegap-app-developer/issues/418

**Closed by timkim** 2016-04-28 20:29 UTC
Labels: duplicate
