### ISSUE TITLE
App freeze with NSURLSession delegate problems

### ISSUE THREAD

**Issue by xeonarno** [phonegap/phonegap-app-developer#300] opened 2015-06-06 23:50 UTC
Hi,

The NSURLSession delegate functions (ContentSync.m Line 133): 
```ObjectiveC
- (void) URLSession:(NSURLSession*)session downloadTask:(NSURLSessionDownloadTask*)downloadTask didFinishDownloadingToURL:(NSURL *)downloadURL;
```
and the function (ContentSync.m Line 154): 
```ObjectiveC
- (void)URLSession:(NSURLSession*)session downloadTask:(NSURLSessionDownloadTask *)downloadTask didWriteData:(int64_t)bytesWritten totalBytesWritten:(int64_t)totalBytesWritten totalBytesExpectedToWrite:(int64_t)totalBytesExpectedToWrite;
```
Are never call so the application became impossible to use !!!! please help 

Test done on : Build on 8.2 and target for 6.0

**Comment by imhotep** [comment] 2015-06-08 18:47
Hi @xeonarno,

I cannot reproduce your issue. Are you not getting "progress" or "complete" events ? Which method are you calling in JS and how are you calling it ?

**Comment by xeonarno** [comment] 2015-06-11 15:47
the process :
My configuration is a MacBook mid2012 with osx 10.9.5 with Xcode 6.2
I start on my computer de "phonegap serve" command. the ip address from the local network appear : something like 192.168.1.11:3000

I tested on an Android (LG g3- Lolipop) and an iPhone (4S on 6.0 or 5S on 8.3). Nothing works : 

First the screen : Downloading.... and then nothing appear or append. 
My app at the beginning has 500Mo but to test I reduced it to 15 Mo nothing append too.
on the terminal, nothing append too, the only message was : 

[phonegap] starting app server...
[phonegap] listening on 192.168.1.11:3000
[phonegap] 
[phonegap] ctrl-c to stop the server
[phonegap] 

And nothing after. 

I tried to log on the source on iOS and the both delegate function previously defined are never called. 
It seems that the problem appear after the last update on App Store (around mid-may). 
It is like the delegate object define for the NSURLSessionDownloadTask is never called... There is some logs about background thread when you call the command.

I get the zip from the url of the download and it works on my browsers on desktop.

Please help ! I became problematic on professional project.

**Comment by mwbrooks** [comment] 2015-09-11 22:50
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Closed by mwbrooks** 2015-09-11 22:50 UTC
