### ISSUE TITLE
cannot pair with the desktop app

### ISSUE THREAD

**Issue by nicetohaveyou** [phonegap/phonegap-app-developer#396] opened 2016-01-16 16:02 UTC
The desktop app is showing
Server is running on multiple IP addresses:

and three different ip addresses are shown.

Connecting any of the ips from my windows phone app gives me two errors:

Unable to download archive from the server.

Unable to properly connect to the server.

Please let me know, whats the issue.

**Comment by surajpindoria** [comment] 2016-01-18 18:46
Hi @nicetohaveyou,

This is a duplicate of another issue already filed, therefore I will be closing it. Please take a look at https://github.com/phonegap/phonegap-app-developer/issues/351 for some potential solutions.

**Closed by surajpindoria** 2016-01-18 18:46 UTC
