### ISSUE TITLE
Can't run with Construct 3 Engine

### ISSUE THREAD

**Issue by QuasarX** [phonegap/phonegap-app-developer#561] opened 2019-07-01 13:57 UTC
IDC ABOUT BUGS

**Comment by JeFawk** [comment] 2019-08-19 13:13
I also run into this problem.

**Comment by JeFawk** [comment] 2019-08-19 13:15
This is my approach (just export as their cordova project), drag and drop on app -> black screen

https://github.com/Scirra/Construct-3-bugs/issues/3228

**Comment by AshleyScirra** [comment] 2019-08-19 13:19
For the PhoneGap developers: the problem is cordova-plugin-file can read files from the app bundle on mobile, but in the desktop app it appears to fall back to reading the sandboxed filesystem API in Chrome. Since Construct 3 games rely on reading files from the app bundle to load, it won't work in the desktop app unless cordova-plugin-file can also read files from the app bundle. In general the emulator should work the same as a real device or problems like this will be inevitable!

**Closed** 2019-08-19 14:35 UTC

**Comment by JeFawk** [comment] 2019-08-20 09:07
Seems @QuasarX had a teenage fit, this report can safely be deleted now, a pity.
