### ISSUE TITLE
phonegap app for ios not working

### ISSUE THREAD

**Issue by anooppsagar** [phonegap/phonegap-app-developer#510] opened 2017-10-03 12:05 UTC
app not rendering properly

Dont know why, whether the problem is in my phone or in the app

![21413](https://user-images.githubusercontent.com/32484356/31124211-09aab152-a861-11e7-8e26-8829c7d6f349.jpg)

**Comment by timkim** [comment] 2017-10-03 18:02
Hi @anooppsagar 

It's a problem with the dev app. An update has been submitted to the app store and should be available soon. Also, this ticket is a duplicate of this one: https://github.com/phonegap/phonegap-app-developer/issues/508 so I'll be closing this one.

**Closed by timkim** 2017-10-03 18:02 UTC
