### ISSUE TITLE
iPhone 6 displaying at smaller screen size.

### ISSUE THREAD

**Issue by chadwhitaker** [phonegap/phonegap-app-developer#277] opened 2015-03-18 20:50 UTC
I'm using the PhoneGap developer app for testing my app, but it appears to it's displaying my app at a reduced screen size on my iPhone 6. When I use PhoneGap Build and load the app, everything is displayed at the proper resolution.

Am I missing something in my app configuration or is the current [PhoneGap developer app](http://app.phonegap.com/) not optimized for iPhone 6?

**Comment by timkim** [comment] 2015-03-19 20:39
Hi @chadwhitaker 

Hrm, the app should render the same for iPhone 6. I have a feeling that there might be something different between the config.xml in your project and the phonegap developer apps. When you launch your app through the developer app, the developer app don't read your project's config.xml so that could be a reason why it's different. 

This is what the phonegap developer app uses for a config.xml: https://github.com/phonegap/phonegap-app-developer/blob/master/www/config.xml

And if you have something like `<meta name='viewport' content='width=device-width, initial-scale=1, user-scalable=no'/>` in your config.xml, that could be it.

**Comment by chadwhitaker** [comment] 2015-03-20 20:51
Yeah, I am at loss here. Below is a screenshot of my app viewed using the [Apple App Store version of the PhoneGap developer app](https://itunes.apple.com/app/id843536693) and on the left is my app when compiled using PhoneGap Build. Both screenshots are from the same iPhone 6.

As you can see the resolution is smaller when opened on the Apple App Store version of the PhoneGap developer app. It almost appears that it is running at the resolution of an iPhone 5.

I also pulled this repo and built it using PhoneGap Build. When I open the developer app using my build, it appears to run at the proper resolution. 

![phonegap-res](https://cloud.githubusercontent.com/assets/433078/6760644/d1afc748-cf18-11e4-9f9b-aa45a6abfa46.png)

**Comment by chadwhitaker** [comment] 2015-03-23 18:48
@timkim I just pulled this repo and built the iOS inside of xcode and ran it on my iPhone 6. Below are my results:

When I launch the app, the status bar is at the proper iPhone 6 resolution.
![img_0304](https://cloud.githubusercontent.com/assets/433078/6787801/1eb41cb4-d163-11e4-8c10-fc617261c3f0.PNG)

After fully loaded, you can see that the app is no longer at the proper resolution.
![img_0305](https://cloud.githubusercontent.com/assets/433078/6787823/420ebe26-d163-11e4-89a8-718548c4cb42.PNG)

**Comment by timkim** [comment] 2015-03-23 19:06
Hi @chadwhitaker 

Very strange results. From the first picture of the new posts, it seems like you have two status bars!? I wonder if this might be a problem with the status-bar plugin for iPhone 6? Hrm, I'll have to run some tests on my end but in the mean time, you could try adding this bit of JS `StatusBar.overlaysWebView(true);`

**Comment by chadwhitaker** [comment] 2015-03-23 19:09
Hey @timkim 

There actually isn't two status bars. The screenshot is actually the transition from the splash screen to the actual app. It was hard obtaining a screenshot of just the splash screen—fast transition :)

**Comment by chadwhitaker** [comment] 2015-03-23 19:12
Also note: It's not only the status bar resolution that's the issue. The entire app is running at the smaller resolution as seen in my first post. Just wanted to clarify that.

**Comment by timkim** [comment] 2015-03-23 19:12
Ohhh haha. Must've taken a few tries :P 

But ya, I'll still give this a few tests on my side. I don't have an iPhone 6 on me so I'll have to ask a team member who has one.

**Comment by chadwhitaker** [comment] 2015-03-23 19:16
Thanks. I hope to find a solution to this. I'm using my iPhone 6 to design and test, so it's difficult to see the final product unless I build and load the app directly which can be time consuming. 

I also built the PhoneGap developer app using PhoneGap CLI 4.2.0. The developer app loaded at the proper resolution, but it doesn't pass the "Loading..." screen.

Do you think this is an issue of an out dated version of PhoneGap to build the .ipa?


![img_0307](https://cloud.githubusercontent.com/assets/433078/6788385/1ce62b08-d167-11e4-8491-6f0b6d7bcebf.PNG)

**Comment by mwbrooks** [comment] 2015-03-23 19:58
@chadwhitaker I've got an iPhone 6 and I'll give it a test to see if I can help recreate your scenario! I'm a little packed today, so I'll likely respond tomorrow morning. :)

**Comment by chadwhitaker** [comment] 2015-03-23 21:01
Thanks, @mwbrooks! I look forward to your findings.

**Comment by mwbrooks** [comment] 2015-03-24 21:44
Afternoon @chadwhitaker,

Today @shazron and I dove into this problem and I think we've figured it out. First off, you're not crazy. The iPhone 6's resolution is being scaled down.

The PhoneGap Developer App's latest App Store release [is running Cordova-iOS 3.6.3](https://github.com/phonegap/phonegap-app-developer/blob/master/platforms/ios/cordova/version#L27). This release added the architecture changes required to build iOS 8 apps, but it had some missing features. One missing feature was the [iPhone 6 launch image](https://github.com/apache/cordova-ios/blob/master/bin/templates/project/__PROJECT_NAME__/Resources/splash/Default-667h.png), which was added in Cordova-iOS 3.7.0. Since the launch image is missing, the iPhone 6 app's resolution is down-scaled to 568px in height (iPhone 5). The full details are captured in [CB-7647](https://issues.apache.org/jira/browse/CB-7647).

We've had the latest release held back because we're working at solving some Single Origin Policy restrictions of the PhoneGap Developer App. After releasing this feature, we will bump to Cordova-iOS 3.8.0, since Cordova-iOS 3.7.0 has some bugs in the JavaScript bridge and URL handling.

Now, looping back to your PhoneGap Build version of the application. Currently, PhoneGap Build [defaults to building all applications using Cordova 3.7.0](http://docs.build.phonegap.com/en_US/configuring_preferences.md.html#Preferences). And as mentioned above, Cordova 3.7.0 introduces the iPhone 6 splash screen, which allows the app to run at it's native resolution.

So the basic summary is that today, the PhoneGap Developer App on an iPhone 6 will render at the iPhone 5's resolution.

I'm going to leave the issue open as a reminder for us to upgrade Cordova-iOS to 3.8.0 and notify you when it's ready.

I hope that helps a little!

**Comment by chadwhitaker** [comment] 2015-03-25 21:47
Hey @mwbrooks,

Thank you so much for investigating this. Do you have an ETA on this release? Or how difficult would it be if I built the Developer app inside Xcode using 3.8.0? I have experience with deploying apps from Xcode to my device. I'm just to sure what's involved with updating the /platforms/ios code to work with a newer version. 

I ask because I would like to build out my html/css using my iPhone 6 in realtime on the actual device. 

Thanks!

**Comment by mwbrooks** [comment] 2015-03-27 23:26
Hi @chadwhitaker,

We're testing the app now, so I'd be optimistic of an App Store release around the second week of April.

Building it locally shouldn't be too difficult. We can work through it together as well, on this issue!

Typically the steps would include:

```
phonegap platform add ios@3.8.0
phonegap build ios
phonegap run ios --emulator
# or you can open the platforms/ios/ project in Xcode at this point
# you can also attach the Safari RemoteWebInspector to the simulator instance for debugging
```

Of course, problems always come up. Next week, let's work through this together, if you'd like! Hit me up on Hangout/Gtalk @ michael@michaelbrooks.ca or we can chat here.

Michael

**Comment by chadwhitaker** [comment] 2015-03-28 18:41
Thanks @mwbrooks! You're the best!

I'll see what I can produce over the weekend and follow up with you next week.

**Comment by imperyal** [comment] 2015-05-14 13:49
Hello! Do you have any news on this subject? I'm experiencing the same issue...

**Comment by chadwhitaker** [comment] 2015-05-14 17:45
@imperyal I forked this app and updated it to work with iPhone 6.

You can clone this repo https://github.com/demandfood/phonegap-app-developer and then run `phonegap run ios --device`

**Comment by imperyal** [comment] 2015-05-14 18:18
Ok ;) I will check it out. Thank you!

**Comment by firsname-markus** [comment] 2015-06-19 06:25
Is there anything new to this issue.. I'm still having the scaling problem with the Phonegap Developer app from the app store..

**Comment by gabereiser** [comment] 2015-08-02 07:39
Same as firsname-markus

**Comment by mwbrooks** [comment] 2015-09-11 22:46
The scaling problem should be resolved in the next release. I've attached it to the proper milestone.

**Comment by mwbrooks** [comment] 2015-09-11 22:46
The scaling problem should be resolved in the next release. I've attached it to the proper milestone.

**Comment by surajpindoria** [comment] 2015-09-21 23:09
I was able to reproduce this issue using version 1.5.5 of the app, but it has been fixed in the `platforms-as-artifacts` branch

**Closed by surajpindoria** 2015-09-21 23:09 UTC
Labels: bug

**Comment by mwbrooks** [comment] 2015-09-21 23:11
Awesome! The next release should be landing in app stores soon.

**Comment by JohnHanks** [comment] 2015-10-16 21:15
I am having the same issue but in android.

Developer app shows my layouts in proper size

Build.Phonegap.Com builds with my text and css super small

**Comment by szugyi** [comment] 2016-03-08 21:26
Having the same issue as @JohnHanks.

**Comment by infinitysky** [comment] 2016-04-17 23:11
In my case I do not wish to use the splash screen. I have set  the "launch Image source" to "not use any image". Next I select the "Launch screen file" to "MainViewController" via drop down list. 
The problem was solved.
![snip20160418_1](https://cloud.githubusercontent.com/assets/1997572/14590727/3c7975e8-0545-11e6-8a1d-8b2f7035be17.png)

**Comment by V4NDER** [comment] 2018-04-25 20:13
It is necessary to create properly splashscreen

visit https://www.resource-generator.com
