### ISSUE TITLE
iPad + PhoneGap CLI crashes: "Can't set headers after they are sent."

### ISSUE THREAD

**Issue by cblgh** [phonegap/phonegap-app-developer#299] opened 2015-06-05 14:17 UTC
I recently updated the PhoneGap CLI, running on Windows 7, to version 5.0.0-0.28.1 which works fine on android but fails to work with my iPad.

When the iPad, using the PhoneGap Developer App, connects to the server the CLI crashes with the following output:
```
[phonegap] starting app server...
[phonegap] listening on 192.168.1.23:3000
[phonegap]
[phonegap] ctrl-c to stop the server
[phonegap]

http.js:691
    throw new Error('Can\'t set headers after they are sent.');
          ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:691:11)
    at ServerResponse.res.setHeader (C:\Users\Alex\AppData\Roaming\npm\node_modu
les\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\patch.js:63:
22)
    at ServerResponse.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_module
s\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\patch.js:80:14
)
    at Array.forEach (native)
    at ServerResponse.res.writeHead (C:\Users\Alex\AppData\Roaming\npm\node_modu
les\phonegap\node_modules\connect-phonegap\node_modules\connect\lib\patch.js:79:
28)
    at null.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap
\node_modules\connect-phonegap\lib\middleware\zip.js:70:21)
    at EventEmitter.emit (events.js:117:20)
    at Archiver.append (C:\Users\Alex\AppData\Roaming\npm\node_modules\phonegap\
node_modules\connect-phonegap\node_modules\archiver\lib\core.js:317:10)
    at EventEmitter.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\
phonegap\node_modules\connect-phonegap\lib\middleware\zip.js:89:29)
    at EventEmitter.emit (events.js:106:17)
```
I tried removing the app and reinstalling it from the App Store but it had no effect on the CLI crashing.

**Comment by timkim** [comment] 2015-06-08 18:41
Hi @cblgh 

Hrm, usually this error is from the server trying to package up your project and send it out as a zip. Could you tell us if your Windows 7 machine is 32bit or 64 bit and which ios version you have running on your ipad?

**Comment by cblgh** [comment] 2015-06-08 19:43
I'm running Windows 7 64-bit and iOS 7.1.2.

**Comment by timkim** [comment] 2015-06-17 23:50
Hi @cblgh 

Hrm, I'm unable to reproduce the problem on my side, but it does seem others are having similar issues. Can you help us by filling out this questionnaire? https://github.com/phonegap/phonegap-app-developer/issues/306 

Hopefully by gathering enough information about people's spec we can narrow down where the problem is.

**Comment by mwbrooks** [comment] 2015-09-11 22:49
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Closed by mwbrooks** 2015-09-11 22:49 UTC

**Comment by sundbry** [comment] 2015-09-27 06:38
Hi, this problem happens when you use a symlinked www/ directory. The above PR ^^ resolves the underlying issue.

**Comment by andres-torres-marroquin** [comment] 2015-12-08 21:37
@sundbry I can confirm that the symlinks are the issue.
