### ISSUE TITLE
google play shows Phonegap app developer as incompatible for Asus tablet ME172V Android 4.1.1

### ISSUE THREAD

**Issue by ebticbobo** [phonegap/phonegap-app-developer#412] opened 2016-03-24 17:09 UTC

**Comment by surajpindoria** [comment] 2016-03-24 18:06
Please take a look at https://github.com/phonegap/phonegap-app-developer/issues/408.

Unfortunately your device does not meet some minimum standards that we require for our app. You can still manually download the apk and install it yourself and it may work just fine for your needs. But some of the features might not work as intended.

Closing this issue.

**Closed by surajpindoria** 2016-03-24 18:06 UTC
