### ISSUE TITLE
PhoneGap Developer not updating changes (iPhone)

### ISSUE THREAD

**Issue by Tuuuukka** [phonegap/phonegap-app-developer#291] opened 2015-05-28 11:53 UTC
So my problem is this: 

1. I have a test app I created with <code>phonegap create test-app</code>
2. I started mirroring the app with <code>phonegap serve</code>
3. On my iPhone I launch the Developer App and enter the IP and everything is nice and I see the app just fine
4. I make random changes to the index-file and save it, but I can't see the changes on my iPhone (with autoreload or four-finger-tap)

Quitting the Developer App and launching it again does not help, the content of the test app stays the same and no changes are visible. But if I uninstall the Developer App completely on my phone, install it again and then connect to the server again, the test app is updated and the changes are visible. 

The changes also happen automatically on browsers etc. but not on the Developer App.

**Comment by mwbrooks** [comment] 2015-05-28 21:11
@Tuuuukka,

Thanks a lot for the detail!

Before I dive into random suggestions, have you updated to the latest PhoneGap Developer App and the latest PhoneGap CLI?

**Comment by Tuuuukka** [comment] 2015-05-29 06:18
At least <code>phonegap -v</code> gives me <code>5.0.0-0.28.0</code>. And I'm running the server on OSX Mavericks and using iPhone5, if that matters.

Also I just noticed that if I make changes to a file and save it while using the Developer App, the "connecting to device" blinks for a second and then changes back to "device ready". So the connection seems to be ok, the changes just don't show without re-installing the app.

**Comment by mwbrooks** [comment] 2015-05-29 18:38
Thanks for the info @Tuuuukka. The fact that is does auto-reload ("connecting to device" flickers, indicating a refresh) but it does not update the app's content is interesting.

I'm not sure if it's related, but #292 is having a different issue on an iPhone 5. I'm looking around for an iPhone 5 device to test on, so I'll report back on what I find.

**Comment by Tuuuukka** [comment] 2015-06-01 19:14
Thanks again @mwbrooks, I will check that one out.

Today I set up a new server on Ubuntu (with a new IP address of course) and connected to it from my iPhone. It actually showed the app from the Mac server which wasn't even running at the time. And again, after re-installing the Developer App and reconnecting to the (Ubuntu) server, the App was refreshed just fine.

**Comment by PierBover** [comment] 2015-06-05 02:19
I?m having a similar issue.

For some reason I save a file, and the CLI displays the message "file changed" but the app does not refresh. Sometimes even when tapping the app with 4 fingers the app refreshes but it's still using the old files.

I'm using latest version of the CLI, and the iOS app.

I've given up on using the app for development except for the ocasional device testing.

**Comment by mwbrooks** [comment] 2015-06-05 17:21
Hi @PierBover thanks for the info. It's actually very useful to know that the file change was detected by the CLI. What operating system is your computer running?

**Comment by PierBover** [comment] 2015-06-05 18:00
I'm on OSX 10.9

**Comment by PierBover** [comment] 2015-06-05 18:02
BTW, this behaviour is not consistent but I haven't been able to detect what triggers it. It seems almost random.

**Comment by timkim** [comment] 2015-06-18 00:24
Hi @Tuuuukka and @PierBover 

We've made some updates to the app for the reload issue. Please update your app and see if that works for you.

**Comment by mwbrooks** [comment] 2015-09-11 22:48
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Closed by mwbrooks** 2015-09-11 22:48 UTC
Labels: bug

**Comment by tylermakin** [comment] 2016-12-10 00:47
@mwbrooks This may be caused by a bug on the HTML or JS being tested. I a have a bug in my index file which also causes the PhoneGap Developer app to stop updating. When I load a functional `index.html` file I can see updates, but if I copy and paste the valid index file with the buggy one, the updates stop working.

Just like @PierBover I am seeing the changes picked up by the CLI but not on my phone.

**Comment by mwbrooks** [comment] 2017-01-05 19:54
@tylermakin that makes sense. If an error causes the page to fail to load, then the update/refresh logic would also fail to load. I've created a separate issue to discuss improving this and link it back here: https://github.com/phonegap/phonegap-app-developer/issues/474 If possible, could you provide a small example that reproduces the error?

**Comment by tylermakin** [comment] 2017-01-06 18:57
@mwbrooks I do not recall the specific bug that caused my script to stop but anything that prevents a page from loading properly should do the trick.

A simple bug that should cause this issue is calling an undefined variable:
```
console.log('This will appear on console');
var b = a;
console.log('This will not appear in console');
```

Adding this to your JavaScript should throw an error and stop any further JS from loading, which seems to be what is causing the PhoneGap Developer app from refreshing.

**Comment by mwbrooks** [comment] 2017-01-09 17:14
Thanks @tylermakin and thanks for quoting it in #474 :)
