### ISSUE TITLE
The interface look are different in phonegap developer and build apk

### ISSUE THREAD

**Issue by technicusinfotech** [phonegap/phonegap-app-developer#263] opened 2015-01-14 10:01 UTC
![apk](https://cloud.githubusercontent.com/assets/6839973/5736965/f8ae0e9e-9c01-11e4-996c-6188c929911b.jpg)
![developerapp](https://cloud.githubusercontent.com/assets/6839973/5736966/f91a9dd4-9c01-11e4-8624-40db1cdb5426.jpg)

i am building a very basic app with jquery mobile and phonegap.and when i m vewing my app using phonegap developer desktop app then its view as i want but when i build the app and install the apk in my phone then it show different view.as i have attached the image also the first image is of installed apk and second is of the phonegap developer app

Please tell me where i m going wrong.

**Comment by timkim** [comment] 2015-01-14 21:34
Hi @technicusinfotech 

This is not something I've not seen before. Could you provide the code so we could take a closer look?

**Comment by technicusinfotech** [comment] 2015-01-15 00:28
hi @timkim
the source code is attached

Warm Regard

Shubham Shrivastava
Chief Executive Officer

Technicus Infotech
Jai Maa Bhagwati kutir,
8/128,Janta Press Lane,
Ganga Sagar Chowk,Madhubani
Bihar,India 847211
Contact:- +91-8556093704
Skype: technicusinfotech

www.technicusinfotech.com

CallSend SMSAdd to SkypeYou'll need Skype CreditFree via Skype

Date: Wed, 14 Jan 2015 13:34:06 -0800

**Comment by technicusinfotech** [comment] 2015-01-15 00:34
hi @timkim

i have send u the mail with subject "The interface look are different in phonegap developer and build apk" and the source code is attached in that mail.

thanks.

**Comment by timkim** [comment] 2015-01-29 22:46
Hi @technicusinfotech 

Sorry about the late reply but I don't think I've received and such email? Which email address did you send it to? Should be timk@adobe.com.

**Comment by jgw96** [comment] 2015-04-03 22:32
Hey a client of mine was having the same issue. The app looked completely different for him in the developer app than the actual build did. Its almost as if a lot of the CSS wasnt even executed. Im using the latest version of Phonegap Build and he had the problem on Android and IOS.

**Comment by technicusinfotech** [comment] 2015-04-03 22:41
please provide me the look of the different interface that u r geeting

**Comment by jgw96** [comment] 2015-04-03 22:44
@technicusinfotech
Don't have the screenshots as they are on my clients phone but its almost as if the CSS wasn't executed. It looked as if all my positioning wasn't doing anything and all of my opacity settings weren't doing anything

**Comment by technicusinfotech** [comment] 2015-04-03 22:59
@jgw96

Without seeing anything i can't help u if u have the build apk then send to me so i can see...or if u have code

**Comment by jgw96** [comment] 2015-04-03 23:13
Sorry its a proprietary app so I can't show the code.

**Comment by technicusinfotech** [comment] 2015-04-03 23:17
Okk give the apk

**Comment by jgw96** [comment] 2015-04-03 23:18
Like I said its a proprietary app which means I can't share the code or the
apk

**Comment by technicusinfotech** [comment] 2015-04-03 23:23
Then i wont able to help u

**Comment by bholmes451** [comment] 2015-04-04 22:43
An update on this.  I compiled the latest 1.4.x and this is still a problem.  I believe it is caused by the scaling on the iPhone 6 because I view the app on other environments (android, iPod Touch) it looks just fine.  You could always try contacting Adobe directly to help you with your proprietary version or see if there are consultants you could pay to help you (under nda, etc).  Here is the link for the Adobe PhoneGap contact page: http://phonegap.com/about/contact/

Ben

**Comment by mwbrooks** [comment] 2015-09-11 22:43
We're updating the build process, which may help with this issue. Let's check back on it after the next release.

**Comment by surajpindoria** [comment] 2015-09-21 23:12
I was able to reproduce this issue but it was fixed in an update to `cordova-android`. Updating Cordova/PhonGap version fixed the problem.

**Closed by surajpindoria** 2015-09-21 23:12 UTC
Labels: bug

**Comment by mwbrooks** [comment] 2015-09-21 23:27
Thanks for testing it out @surajpindoria. The next release is coming soon and includes this fix - you can track it on the `platforms-as-artifacts` branch / milestone.
