### ISSUE TITLE
Newbie Question - Phonegap Desktop & Android Phonegap app

### ISSUE THREAD

**Issue by shetaan819** [phonegap/phonegap-app-developer#301] opened 2015-06-11 23:43 UTC
I'm attempting to connect the Android Phonegap app for the first time and am receiving a download error on the phone.

The server logs in Phonegap Desktop displays the following when I attempt to press 'Connect' -  
404/_api_/appzip

After attempting to download, the following error is displayed on the handset - 'Unable to download archive from the server.  Please upgrade the Phonegap CLI or check your network settings'.

I've been able to confirm I have the latest CLI and both are on the same WiFi network (the server is running correctly on Phonegap Desktop).

Anyone know how to get around this issue ?

**Comment by mwbrooks** [comment] 2015-06-11 23:55
Hey @shetaan819,

Thanks a bunch for submitting the issue and it's totally not a newbie question. This is a problem that we're seeing a small group of users have. We're having a difficult time trying to recreate the issue as well.

Mind if I ask for a little more information?

- What operating system are you using? If Windows, 32-bit or 64-bit?
- What phone platform are you using?
- Are you using the PhoneGap Desktop or CLI? It sounds like the Desktop.
- How large is the `www/` folder in your project?
- How many files are in the `www/` folder in your project?

Since you're receiving a `404 /__api__/appzip` (super helpful btw), it makes me think that the issue is on the system-side and not the phone-side. Can you try to:

1. Open your PhoneGap Desktop App (or CLI) and start a project
1. Open your desktop browser (Safari or Chrome, please) 
1. Browse to `http://x.x.x.x:3000/__api__/appzip`
1. Do you see a `404` or `200` response?
1. If a zip is downloaded, can you unzip it or is there an error?

Thanks!
Michael

**Comment by agolia14** [comment] 2015-06-12 03:09
I am also having the same problem. I am running PhoneGap Desktop on my windows 64-bit laptop. While I tried to type the URL provided by you then I got following line in return:

Cannot GET /_api_/appzip
![phonegap error](https://cloud.githubusercontent.com/assets/11542640/8122909/8fe57058-10de-11e5-81a6-d19bf874eca9.png)

**Comment by agolia14** [comment] 2015-06-12 03:13
and the /www folder is of 1.40MB having 5 folders, 2 html pages and a png image

**Comment by mwbrooks** [comment] 2015-06-12 05:18
Hi @agolia14, thanks for the info!

For the URL, it is actually a double underscore (`__`). In your example, you used a single underscore (`_`). I know, totally weird and not intuitive. :) I'd really be interested in your results for that URL (and the reported response in the Desktop app - it's reported in the terminal, which is the window icon on the left-panel).

Thanks!
Michael

**Comment by shetaan819** [comment] 2015-06-12 16:51
mwbrooks,

Thanks for your help !  I get the following when I start the project in the Phonegap Desktop app, and go to the following http://10.0.1.17:3000/__api__/appzip - 

Cannot GET /__api__/appzip

What operating system are you using? If Windows, 32-bit or 64-bit? Mac OS X Yosemite 10.10.3
What phone platform are you using? I have installed Android, iOS, Browser.
Are you using the PhoneGap Desktop or CLI? It sounds like the Desktop. I have used Desktop however I've also installed CLI following the instructions here - http://docs.phonegap.com/en/edge/guide_cli_index.md.html#The%20Command-Line%20Interface

How large is the www/ folder in your project? The www/ folder in my /usr/local/bin/appSample project is 1.5MB

How many files are in the www/ folder in your project?
81 items (If I open the index.html file I'm able to see the page in my browser, Safari)

**Comment by Oleg24** [comment] 2015-06-12 17:31
Unfortunately I am currently running into the same issue.  I'm attempting to run the standard "Hello World" application.  

What operating system are you using? If Windows, 32-bit or 64-bit?  **Mac OS X 10.9.5** 
What phone platform are you using?  **Android** 
Are you using the PhoneGap Desktop or CLI? **I have both installed, but attempting to run with the Desktop**
How large is the www/ folder in your project? **1.5MB**


![screen shot 2015-06-12 at 10 30 34 am](https://cloud.githubusercontent.com/assets/7278723/8135705/1e4edc30-10ee-11e5-82f8-f71001392312.png)

**Comment by mwbrooks** [comment] 2015-06-16 20:02
Hi @Oleg24,

Thanks for the screenshot! I'm also running OS X (10.10.3) and it looks like you're using Google Chrome. I've tried it on my end and everything looks good.

A few questions:

1. Are you using the PhoneGap Desktop v0.1.7 (click the sidebar `? > About`)?
2. Are you running a software anti-virus or firewall? (It's a stretch, I know).

**Comment by shetaan819** [comment] 2015-06-17 13:54
fyi, I was running v0.1.5 but will now try with v0.1.7.

**Comment by mwbrooks** [comment] 2015-06-17 19:41
Hi @shetaan819,

Great! I would expect `v0.1.5` to return the response `Cannot GET /__api__/appzip`, so I hope the `v0.1.7` upgrade helps.

**Comment by timkim** [comment] 2015-06-17 23:47
Hi everyone in this thread. 

We're still diagnosing the problems people are having with their connection issues. Help us out by filling out this questionnaire: https://github.com/phonegap/phonegap-app-developer/issues/307.

**Comment by shetaan819** [comment] 2015-06-23 07:18
mwbrooks, 

I can confirm upgrading to v0.1.7 fixed the issue, thanks !

**Comment by Chris108** [comment] 2015-07-16 10:27
Hi,
I also used to have an error message after a long phase of ,,DOWNLOADING....'' The reason was the firewall (Linux, OpenSuSe). 
As soon as I turn the firewall off, it's fine.
Now I try to insert some firewall rules to allow the connection. Can you tell me please what
kind of service this is, the communication between the phonegap developer app and the computer?
Or what the protocol is? TCP? UDP? 
Thanks, Chris108

**Comment by mwbrooks** [comment] 2015-09-11 22:50
Closing since we haven't seen very much activity on this issue. Feel free to reopen.

**Closed by mwbrooks** 2015-09-11 22:50 UTC
Labels: bug

**Comment by autogrammer** [comment] 2016-07-17 23:49
Restarting my router fixed the problem for me.

**Comment by jherico123** [comment] 2016-09-25 18:22
i have a problem like this.
my laptop and my mobile on the same wifi
laptop windows 64 bit
my mobile is android
phonegap desktop v0.3.5
please help me, sory if my english bad

![14435010_10207470037648691_8592417147160464061_o](https://cloud.githubusercontent.com/assets/22432593/18817260/a759ce34-8386-11e6-8466-a045b43c8247.jpg)

**Comment by surajpindoria** [comment] 2016-09-26 18:31
Hi @jherico123,

Can you take a look at this FAQ regarding this issue? There are a bunch of tips that may help with this.

http://docs.phonegap.com/references/developer-app/troubleshoot-faq/#phonegap-developer-app-is-unable-to-download-from-the-server

**Comment by BHunter2889** [comment] 2017-05-09 18:40
@surajpindoria and @jherico123 , I know it's been a while, but that above link did it for me. Also, I had issues when I switched ISPs and had to use their router, it did something with my configured network settings or required additional ones. So I changed some running service settings and that fixed that issue. I wish I could be more specific, but I'm not sure which change did the trick, I should've stepped through it. My apologies. 

For reference, these links set me on the right path, though I didn't do any of these solutions as they're described. The one that I came closes to following was the second link here:

- [SO - How do you set the ip address for Phonegap Developer app
](http://stackoverflow.com/questions/26383245/how-do-you-set-the-ip-address-for-phonegap-developer-app)

- (Best Match) [How to Access localhost on Android over wifi](http://www.mobitechie.com/android-2/how-to-access-localhost-on-android-over-wifi/)

**NOTE:** I am (and always have been before, during, and after the connection issues) hosting via PhoneGap Desktop on my Win10 PC, and connecting via PhoneGap developer app on my iPhone 7 Plus via LAN WiFi. My PC is wired to the router.
