### ISSUE TITLE
[iOS] if CSP is commented out, I get a blank screen 

### ISSUE THREAD

**Issue by shazron** [phonegap/phonegap-app-developer#450] opened 2016-10-29 23:44 UTC
**Description:**
If I comment out my CSP in my index.html, and serve my app to the PhoneGap Developer App, I get a blank (white) screen.

**Steps to repro:**
Comment out your CSP in your index.html, like so:

```
<!-- <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *"> -->
```

$ phonegap serve
Connect to your served app from the PhoneGap Developer App on iOS

**Expected behaviour:**
My app loads.

**Actual behaviour:**
My app does not load.

**Workaround:**
Don't comment out your CSP.

**Versions:**
$ phonegap --version
6.3.4
$ PhoneGap Developer App version 1.7.5

**Comment by timkim** [comment] 2016-10-31 18:30
Hrmmm - I think this is more of a `connect-phonegap` issue. That's where most of the CSP injection happens.

**Comment by shazron** [comment] 2016-10-31 22:57
Attached `www` to repro. 
[www.zip](https://github.com/phonegap/phonegap-app-developer/files/563013/www.zip)

**Comment by shazron** [comment] 2016-10-31 23:04
btw tested on iOS 9.3.4 "iPhone 6 Plus"

**Comment by timkim** [comment] 2016-11-01 18:19
Can't reproduce right now. Closing for now.

**Closed by timkim** 2016-11-01 18:19 UTC
Labels: bug

**Comment by shazron** [comment] 2016-11-01 18:22
Thanks Tim, will re-open when I can bring my code and device in for you.
