### ISSUE TITLE
Can't install thru Play Store in recent tablet

### ISSUE THREAD

**Issue by flyonthenet** [phonegap/phonegap-app-developer#502] opened 2017-09-01 09:07 UTC
Can't install via Google PlayStore in my tablet
Installing APK 1.7.0 manually seems to work fine

Huawei MediaPad T3 10
OS: Android 7.0 - Emui 5.1
CPU: Snapdragon 425
RAM 2GB - Mass storage 16 GB with 3GB free
Screen resolution: 1280x800 (10")

What requirements doesn't meet?

**Comment by surajpindoria** [comment] 2017-09-01 18:12
This is a duplicate of #408. Unfortunately if your device is incompatible, a manual install is the only way to go.

**Closed by surajpindoria** 2017-09-01 18:12 UTC
